name: Build and push

on:
  push:
    branches: [ main ]
    paths: ['Code/Backend/**']
  pull_request:
    branches: [ main ]
    paths: ['Code/Backend/**']

jobs:

  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Code/Backend
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        cd cmd
        go build -o ../build/go-app.exe -v
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: cryogenetics-logistics-solution
        package: Code/Backend/build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        enable-oryx-build: false